appium/dotnet-client

appium-dotnet-driver/appium-dotnet-driver.csproj, appium-dotnet-driver/appium-dotnet-driver.nuspec
This patch enables xmldoc generation:
- during a release build, xmldoc file is generated
- during creation of the nuget package, the xmldoc is included in the nuget package
This enables to see the xml documentation using intellisense:
=> Patch to enable xmldoc

RELEASE_NOTES.md, appium-dotnet-driver/Appium/Android/AndroidDriver.cs, appium-dotnet-driver/Appium/Android/Interfaces/ISendsKeyEvents.cs, appium-dotnet-driver/Appium/AppiumCommand.cs, appium-dotnet-driver/Appium/AppiumDriverCommand.cs, appium-dotnet-driver/appium-dotnet-driver.nuspec, integration_tests/Android/AndroidActivityTest.cs, integration_tests/Android/AndroidKeyPressTest.cs, integration_tests/integration_tests.csproj
Change list: 
- AndroidDriver.KeyEvent() were marked obsolete. They are going to be removed.
- The AndroidDriver.PressKeyCode method was added.
- The AndroidDriver.LongPressKeyCode method was added.
=> The updating of Android key event methods.

appium-dotnet-driver/Appium/AppiumDriver.cs
Very simple, compiler error fix
Added a JSON.net namespace to a file to fix a compiler error
##Details
Added a JSON.net namespace to a file to fix a compiler error
=> Fixing a compiler error: missing JSON.net namespace

RELEASE_NOTES.md, appium-dotnet-driver/Appium/AppiumCommand.cs, appium-dotnet-driver/Appium/AppiumDriver.cs, appium-dotnet-driver/Appium/AppiumDriverCommand.cs, appium-dotnet-driver/appium-dotnet-driver.nuspec, integration_tests/Android/AndroidSessionTest.cs, integration_tests/integration_tests.csproj
- #153 fix 
- #152 fix
These changes (#153 fix & #152 fix) are supposed to be the temporary workaround. I'm and  @SrinivasanTarget are searching for a more consistent solution. It seems it requires some changes on the server side.
- The `SessionDetails` property was added.  This property returns a dictionary of the current session data.
- updated release notes.
=> #153 fix & #152 fix. The `SessionDetails` property

appium-dotnet-driver/Appium/Android/AndroidCommandExecutionHelper.cs, appium-dotnet-driver/Appium/Android/AndroidDriver.cs, appium-dotnet-driver/Appium/Android/AndroidElement.cs, appium-dotnet-driver/Appium/Android/Enums/AutomatorSetting.cs, appium-dotnet-driver/Appium/Android/Interfaces/IHasNetworkConnection.cs, appium-dotnet-driver/Appium/Android/Interfaces/IHasSettings.cs, appium-dotnet-driver/Appium/Android/Interfaces/IStartsActivity.cs, appium-dotnet-driver/Appium/AppiumCommand.cs, appium-dotnet-driver/Appium/AppiumCommandExecutionHelper.cs, appium-dotnet-driver/Appium/AppiumDriver.cs, appium-dotnet-driver/Appium/AppiumWebElement.cs, appium-dotnet-driver/Appium/Interfaces/IHidesKeyboard.cs, appium-dotnet-driver/Appium/Interfaces/IHidesKeyboardWithKeyName.cs, appium-dotnet-driver/Appium/Interfaces/IInteractsWithApps.cs, appium-dotnet-driver/Appium/Interfaces/IInteractsWithFiles.cs, appium-dotnet-driver/Appium/Interfaces/IMobileElement.cs, appium-dotnet-driver/Appium/Interfaces/IPerformsTouchActions.cs, appium-dotnet-driver/Appium/Interfaces/ISendsKeyEvents.cs, appium-dotnet-driver/Appium/Windows/WindowsDriver.cs, appium-dotnet-driver/Appium/iOS/IOSCommandExecutionHelper.cs, appium-dotnet-driver/Appium/iOS/IOSDriver.cs, appium-dotnet-driver/Appium/iOS/Interfaces/IIOSHidesKeyboard.cs, appium-dotnet-driver/Appium/iOS/Interfaces/IPerformsTouchID.cs, appium-dotnet-driver/Appium/iOS/Interfaces/IShakesDevice.cs, appium-dotnet-driver/appium-dotnet-driver.csproj, integration_tests/Android/AndroidSettingTest.cs, integration_tests/integration_tests.csproj
API partial redesign:
- ```OpenQA.Selenium.Appium.Android.Interfaces.ISendsKeyEvents``` was marked obsolete.
- ```Appium.Interfaces.ISendsKeyEvents``` was added. It is implemented by AndroidDriver and WindowsDriver.
- ```OpenQA.Selenium.Appium.iOS.Interfaces.IIOSHidesKeyboard```  was marked obsolete.
- ```OpenQA.Selenium.Appium.Interfaces.IHidesKeyboardWithKeyName``` was added. It extends ```OpenQA.Selenium.Appium.Interfaces.IHidesKeyboard``` and it is implemented by IOSDriver and WindowsDriver.
- ```OpenQA.Selenium.Appium.Android.Interfaces.IHasSettings``` was added. It is implemented by AndroidDriver. Also the ```OpenQA.Selenium.Appium.Android.Enims.AutomatorSetting``` was provided.
- ```OpenQA.Selenium.Appium.iOS.Interfaces.IPerformsTouchID``` was added. It is implemented by IOSDriver. …
=> API partial redesign. Command execution helpers.

appium-dotnet-driver/Appium/AppiumDriver.cs
With the explicit interface implementation is possible to define both methods form RemoteWebDriver and from IExecuteMethod.
This can be applied also to all other methods defined with "new" in AppiumDriver like FindElements, FindElementById, etc. 
Related to [issue 168](https://github.com/appium/appium-dotnet-driver/issues/168)
- [X ] Bugfix (non-breaking change which fixes an issue)
=> Explicit interface impentation, not to hide RemoteWebDriver Execute method

PULL_REQUEST_TEMPLATE.md, README.md, RELEASE_NOTES.md, integration_tests/README.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
=> Fix broken headings in Markdown files

appium-dotnet-driver/Appium/MultiAction/TouchAction.cs
Change "longpress" to "longPress" in TouchAction class
Created issue for this https://github.com/appium/appium-dotnet-driver/issues/180
=> longPress action name fix

appium-dotnet-driver/Appium/Enums/MobilePlatform.cs
Makes them usable for attributes (e.g. as a parameter for a platform specific ignore attribute)
- [ x ] New feature (non-breaking change which adds functionality)
I'd like to be able to use MobilePlatform in attributes of tests where const values are required.
=> Use const for values of MobilePlatform

appium-dotnet-driver/Appium/Enums/MobileSelector.cs, appium-dotnet-driver/Appium/Interfaces/IFindsByIosClassChain.cs, appium-dotnet-driver/Appium/Interfaces/IFindsByIosNSPredicate.cs, appium-dotnet-driver/Appium/MobileBy.cs, appium-dotnet-driver/Appium/iOS/IOSDriver.cs, appium-dotnet-driver/appium-dotnet-driver.csproj, integration_tests/helpers/Caps.cs, integration_tests/iOS/iOSSearchingClassChainTest.cs, integration_tests/integration_tests.csproj
This is to add capability to use class chain selectors for Finding elements.
`            
AppiumWebElement lastSettingsCellItem = MobileAppMgr.CurrentAppDriver.FindElement(MobileBy.IosClassChain("**/XCUIElementTypeCell[-1]"));
string labelAttribute = lastSettingsCellItem.GetAttribute("label");
lastSettingsCellItem.Tap(1, 250);
`
Appium Logs for above code are available [here](https://gist.github.com/rajfidel/cdbe93f1b2ca1e33b6221752cc062c04)
=> Add Find by ios class chain

appium-dotnet-driver/Appium/MultiAction/TouchAction.cs
fixed typo in longPress Action as described in #197
Changed "longpress" to "longPress" in TouchAction.cs class
=> Bugfix for issue #197

appium-dotnet-driver/Appium/AppiumDriver.cs, appium-dotnet-driver/Appium/Interfaces/IHasSessionDetails.cs, appium-dotnet-driver/appium-dotnet-driver.csproj, integration_tests/Android/SessionDetailTest.cs, integration_tests/integration_tests.csproj
- a new interface IHasSessionDetails
- the  IHasSessionDetails is implemented by AppiumDriver
- tests
I have started to add features which have been add to java clint since Jan'17
=> Session details

appium-dotnet-driver/Appium/iOS/IOSCommandExecutionHelper.cs, appium-dotnet-driver/Appium/iOS/IOSDriver.cs, integration_tests/helpers/Caps.cs, integration_tests/iOS/iOSLockDeviceTest.cs
Allowing using locking/unlocking mechanism for .Net client. It's related to:
https://github.com/appium/WebDriverAgent/pull/21
https://github.com/appium/appium-xcuitest-driver/pull/595
Change was determined to use functionality used already in java-client: 
https://github.com/appium/java-client/pull/799
=> Adding handling of locking and unlocking ios devices.

appium-dotnet-driver/Appium/PageObjects/AppiumPageObjectMemberDecorator.cs, appium-dotnet-driver/Appium/PageObjects/ByFactory.cs, appium-dotnet-driver/Appium/PageObjects/Interceptors/ElementInterceptor.cs, appium-dotnet-driver/Appium/PageObjects/Interceptors/ElementListInterceptor.cs, appium-dotnet-driver/Appium/PageObjects/Interceptors/SearchingInterceptor.cs, appium-dotnet-driver/appium-dotnet-driver.csproj, appium-dotnet-driver/packages.config, integration_tests/PageObjectTests/Android/AndroidNativeAppAttributesTest.cs, integration_tests/PageObjectTests/Android/AndroidTestThatChecksAttributeMix1.cs, integration_tests/PageObjectTests/Android/AndroidTestThatChecksAttributeMix2.cs, integration_tests/PageObjectTests/Android/AndroidTestThatChecksAttributeMix3SelendroidMode.cs, integration_tests/PageObjectTests/Android/AndroidWebViewTest.cs, integration_tests/PageObjectTests/Android/SeleniumAttributesCompatipilityTest.cs, integration_tests/PageObjectTests/DesktopBrowserCompatibility/DesctopBrowserCompatibilityTest.cs, integration_tests/PageObjectTests/IOS/IOSNativeAppAttributesTest.cs, integration_tests/PageObjectTests/IOS/IOSTestThatChecksAttributeMix.cs, integration_tests/PageObjectTests/NegativeTests/NoSuchElementTestOnAndroid.cs, integration_tests/PageObjectTests/Other/AndroidTouchActionTest.cs, integration_tests/PageObjectTests/TimeOutManagement/TimeOutManagementTest.cs, integration_tests/PageObjects/AndroidJavaScriptTestPageObject.cs, integration_tests/PageObjects/AndroidPageObjectChecksAttributeMixOnNativeApp1.cs, integration_tests/PageObjects/AndroidPageObjectChecksAttributeMixOnNativeApp2.cs, integration_tests/PageObjects/AndroidPageObjectChecksSeleniumFindsByCompatibility.cs, integration_tests/PageObjects/AndroidWebView.cs, integration_tests/PageObjects/IOSPageObjectChecksAttributeMixOnNativeApp.cs, integration_tests/integration_tests.csproj, integration_tests/packages.config
The upstream Selenium project has marked the `PageFactory` and its
supporting classes deprecated. The code for these classes has been moved
to a [new repository](https://github.com/DotNetSeleniumTools/DotNetSeleniumExtras).
This commit updates the NuGet dependencies for these projects and updates
the namespaces in the source code to refer to the proper objects.
If this PR is not merged, compilation of this code will fail when the implementation of `PageFactory` and its supporting classes has been removed from the Selenium project.
=> Moving page object classes to be based on relocated repo

appium-dotnet-driver/Appium/Service/AppiumCommandExecutor.cs
This commit implements the disposable pattern on AppiumCommandExecutor,
doing everything except actually declaring that the class implements
IDisposable. The upstream Selenium project will be changing the
ICommandExecutor interface to extend IDisposable in the near future, and
this change is required to prevent errors when that change is made.
This PR implements the Disposable pattern as recommended by Microsoft for .NET code. The implementation includes a public `Dispose()` method and a protected `Dispose(bool)` method. As an added code cleanup, it also moves disposal of the service object into the Dispose method for the command executor class. If that change is deemed too risky, that portion of it may be easily …
=> Pseudo-implemnenting IDisposable on AppiumCommandExecutor

appium-dotnet-driver/Appium/AppiumWebElement.cs, appium-dotnet-driver/Appium/Enums/MobileSelector.cs
- Some methods which haven't defined by W3C spec convert selector from them to `css selector`
- In this PR, I've changed to use id, name, class name and tag name directly.
- `GetAttribute` calls JS-command instead of calling `DriverCommand.GetElementAttribute` in W3C spec. In this PR, I've changed to call the command directly.
- related selenium client code: https://github.com/SeleniumHQ/selenium/blob/25d2e542d39768816a83931a4f43e4a006c9e78d/dotnet/src/webdriver/Remote/RemoteWebElement.cs
closes https://github.com/appium/appium-dotnet-driver/issues/266 and https://github.com/appium/appium-dotnet-driver/issues/265
Please provide more details about changes if it is necessary. If there …
=> Get rid of converting selector to css, stop sending JS commands to get attributes

appium-dotnet-driver/Appium/AppiumDriver.cs
AppiumDriver.cs
Allow users to call the W3C related FindBy methods on mobile:
Class
TagName
Name
Id
Completes #268
=> Overwrite w3c related FIndBy methods to adapt to mobile driver

src/Appium.Net/Appium/AppiumDriver.cs
Fixes https://github.com/appium/appium-dotnet-driver/issues/265 for Page Objects as well.
=> Fixes "css selector" issue when using id, name, class name and tag name strategies with Page Objects

src/Appium.Net/Appium/Android/AndroidCommandExecutionHelper.cs, src/Appium.Net/Appium/Android/AndroidDriver.cs, src/Appium.Net/Appium/AppiumCommandExecutionHelper.cs, src/Appium.Net/Appium/AppiumDriver.cs
Deleted android specific part of code about pushing file and moved it back to appium driver (same logic for iOS).
=> Enable pushing files for both android and iOS

src/Appium.Net/Appium/Service/AppiumLocalService.cs, test/integration/ServerTests/AppiumLocalServerLaunchingTest.cs
Added capability to redirect the Appium Local Service output similar to the way Java client does this - https://github.com/appium/java-client/blob/98daabe3943b606c5416818b73add493d889cc94/src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java#L212
Even though the name of the branch suggests that we're redirecting the Error as well, it doesn't really make sense to do so (this was my initial intention - hence the name of the branch).
As a difference between the .NET client and the Java client, I have chosen not to redirect to `Console.Out` by default (see https://github.com/appium/java-client/blob/98daabe3943b606c5416818b73add493d889cc94/src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java#L64) since there are issues in the way some xUnit …
=> Adds functionality that allows redirecting the AppiumLocalService process output to Console to allow easier debugging

src/Appium.Net/Appium.Net.csproj, src/Appium.Net/Appium/AppiumCommand.cs, src/Appium.Net/Appium/AppiumDriver.cs, src/Appium.Net/Appium/AppiumDriverCommand.cs, src/Appium.Net/Appium/Interactions/InteractionInfo.cs, src/Appium.Net/Appium/Interactions/PointerInputDevice.cs, test/integration/Appium.Net.Integration.Tests.csproj, test/integration/Windows/PentTest.cs, test/integration/Windows/StickyNotesTest.cs
Enable AppiumDriver to perform W3CWebDriver Actions and implement support for additional pointer interaction attributes such as pressure, twist, tilt etc.
I've brought these changes from https://github.com/timotiusmargo/appium-dotnet-driver/pull/1.
Also the integration tests were brought from https://github.com/Microsoft/WinAppDriver/tree/master/Samples/C%23/StickyNotesTest
We needed these changes in order to tap on a specific coordinate in our test for our UWP application.
More details can be found here - https://github.com/Microsoft/WinAppDriver/issues/229
I admit I'm not too familiar with the overall design of this feature, so probably it makes sense to reach out to the guys at …
=> Adds pointer input device extension

.editorconfig
Extended the 4-space indent style to include .cs files in the editorconfig
This should reduce a simple form of re-work needed by contributors and reviewers. This was added as a new section within the editorconfig to preserve the existing settings for other file types. If 4-space indentation is desirable across all project files, this could be simplified to a single section of `[*]`.
=> Adjusted editorconfig - spaces in cs files

src/Appium.Net/Appium/AppiumWebElement.cs
Fixes https://github.com/appium/appium-dotnet-driver/issues/328
Contains overrides for `AppiumWebDriver` methods:
FindElementByClassName
FindElementByName
FindElementById
FindElementByTagName
the commands get translated to a CSS selector which does not work.
Changes are the same as in https://github.com/appium/appium-dotnet-driver/pull/302
=> CSS selector fix for findElementsFromElement()

src/Appium.Net/Appium/AppiumCapabilities.cs
ToDictionary() called itself so it caused StackOverflowException.
Added reflection mechanism to get internal capabilities dictionary in
DesiredCapabilities class.
Reordered `usages` block.
- [ x ] Bugfix (non-breaking change which fixes an issue)
Tested with code from issue:
````C#
AppiumOptions options = new AppiumOptions();
options.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
options.AddAdditionalCapability(MobileCapabilityType.DeviceName, "9886785356548358");
options.AddAdditionalCapability(MobileCapabilityType.AutomationName, "UiAutomator2");
options.AddAdditionalCapability("appPackage", "com.test.acc");
options.AddAdditionalCapability("appActivity", "com.test.acc.MainActivity");
options.AddAdditionalCapability("chromedriverExecutableDir", …
```
=> Fix for #338 - StackOverflowException in AppiumOptions.ToDictionary()

src/Appium.Net/Appium/Enums/AppState.cs
Changed `RunningInBackgroud` to `RunningInBackground`
This could be potentially breaking when someone already used the wrongly spelled enum.
=> Fixed spelling error for AppState Enum

src/Appium.Net/Appium/Enums/AndroidMobileCapabilityType.cs
Add AutoGrantPermissions key name to AndroidMobileCapabilityType.
The _autoGrantPermissions_ specified in the docs but absents like const.
Description was taken from [Appium Desired Capabilities](http://appium.io/docs/en/writing-running-appium/caps/index.html#appium-desired-capabilities)
=> Add AutoGrantPermissions key name to AndroidMobileCapabilityType

CHANGELOG.MD, src/Appium.Net/Appium.Net.csproj, src/Appium.Net/Appium/Mac/MacDriver.cs, src/Appium.Net/Appium/Mac/MacElement.cs, src/Appium.Net/Appium/Mac/MacElementFactory.cs, test/integration/Appium.Net.Integration.Tests.csproj, test/integration/Mac/AlertTest.cs
Add MacDriver for appium-mac-driver https://github.com/appium/appium-for-mac
I simply add MacDriver which has 'Mac' platform.
https://github.com/appium/appium-dotnet-driver/issues/382
Below is an example to run MacDriver. I've marked as ignore to functional test not to run it on CI.
```
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"deviceName":"Mac","platformName":"Mac"},"capabilities":{"firstMatch":[{"platformName":"Mac"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"deviceName":"Mac","platformName":"Mac"},null,{"firstMatch":[{"platformName":"Mac"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1577026621045 (23:57:01 GMT+0900 …
```
=> feat: Add MacDriver

CHANGELOG.MD, src/Appium.Net/Appium/AppiumDriver.cs, src/Appium.Net/Appium/Interfaces/IHidesKeyboard.cs
- IHidesKeyboard is now exposes "key" and "strategy" overloads; Resolve (#390)
- IHidesKeyboard no longer implement (inherit) IExecuteMethod - inheritance redundancy and a cleaner interface; Resolve (#389)
=> resolve (#390) and (#389)

CHANGELOG.MD, src/Appium.Net/Appium/Interfaces/IPerformsTouchActions.cs
Interfaces cleanup.
IPerformsTouchActions no longer implement (inherit) IExecuteMethod - inheritance redundancy and a cleaner interface.
=> resolved (#392)

src/Appium.Net/Appium/Android/AndroidDriver.cs, src/Appium.Net/Appium/Android/AndroidElement.cs, src/Appium.Net/Appium/Android/Enums/ListDirection.cs, src/Appium.Net/Appium/Android/UiAutomator/AndroidUiScrollable.cs, src/Appium.Net/Appium/Android/UiAutomator/AndroidUiSelector.cs, src/Appium.Net/Appium/Android/UiAutomator/TerminatedStatementBuilder.cs, src/Appium.Net/Appium/GuardClauses.cs, src/Appium.Net/Appium/Interfaces/IFindByAndroidUIAutomator.cs, src/Appium.Net/Appium/Interfaces/IUiAutomatorStatementBuilder.cs, src/Appium.Net/Appium/MobileBy.cs, test/integration/Android/AndroidUiScrollableTests.cs, test/integration/Android/AndroidUiSelectorTests.cs, test/integration/Android/ElementTest.cs
- Added 2 new fluent-builder style classes (`AndroidUiSelector`, `AndroidUiScrollable`) for building valid `UiSelector` and `UiScrollable` calls.
- Added new interface `IUiAutomatorStatementBuilder` which both new classes implement
- Added method overloads to `IFindByAndroidUIAutomator`
- `FindElementByAndroidUIAutomator(IUiAutomatorStatementBuilder)`
- `FindElementsByAndroidUIAutomator(IUiAutomatorStatementBuilder)`
- Added ctor overload to `ByAndroidUIAutomator`
- `ByAndroidUIAutomator(IUiAutomatorStatementBuilder selector)`
- Added static `By.AndroidUIAutomator(IUiAutomatorStatementBuilder)` overload
I have not submitted a doc change as there doesn't seem to currently be a good …
=> feat: Added builder pattern for creating valid ByAndroidUIAutomator statements

src/Appium.Net/Appium/Service/AppiumLocalService.cs, src/Appium.Net/Appium/Service/AppiumServiceBuilder.cs
`AppiumLocalService` now honors environment variables set in the `AppiumServiceBuilder`.
I attempted to write a test for this, however there are very few (and very specific) uses of environment variables in Appium. It would make sense to have a test in the `StartingAppLocallyTest` class, but I believe Appium itself doesn't use any environment variables. The only way to test this that I am aware of is to override `JAVA_HOME` or `ANDROID_HOME` while attempting to start an Android session. Setting one of those to an invalid value should cause the session to fail and throw an exception, proving that the custom environment variable was set (assuming the session would have otherwise …
=> fix: Custom environment variables are now correctly applied to Node process

src/Appium.Net/Appium/Service/AppiumServiceBuilder.cs, src/Appium.Net/Appium/Service/Options/OptionCollector.cs, test/integration/ServerTests/AppiumLocalServerLaunchingTest.cs
Added option to provide command line arguments to Node in the `AppiumServiceBuilder`.
I've added this feature to support loading Appium from yarn PnP-ified packages (https://next.yarnpkg.com/features/pnp). We needed to pass `--require .pnp.js` to Node in order to include support for reading node packages from zip files. This allows us to reduce build time and have more manageable Node artifacts (~100 zip files rather than 1000s of tiny js files).
=> feat: Provide way to pass arguments to NodeJS

.github/labeler.yml, .github/release-drafter.yml, .github/workflows/main.yml
.github/release-drafter.yml
Add PR labeler [github action](https://github.com/srvaroa/labeler)
Consolidated labels for the release drafter
The purpose of this PR is to enable a github action that will enable automatic labelling of PRs based on the semantic commit type specified in the PR title. This will work in conjunction with the release drafter github action that will produce a draft release note based on items merged in with labels
work and possible use cases. Also …
=> chore: added github action - pr labeler

src/Appium.Net/Appium/ScreenRecording/BaseStartScreenRecordingOptions.cs, src/Appium.Net/Appium/iOS/IOSStartScreenRecordingOptions.cs, test/integration/IOS/ScreenRecordingTest.cs
Added an overload for videoType option
Added the following options for iOS: videoScale, videoFps, videoPixelFormat, videoFilters
closes #400 
closes #404  …
=> feat: add missing iOS Screen recording options

src/Appium.Net/Appium/Android/AndroidDriver.cs, src/Appium.Net/Appium/Android/AndroidElement.cs, src/Appium.Net/Appium/Enums/MobileSelector.cs, src/Appium.Net/Appium/Interfaces/IFindByAndroidViewMatcher.cs, src/Appium.Net/Appium/MobileBy.cs, test/integration/Android/ElementTestEspresso.cs
Just like Espresso's DataMatcher, adding support for ViewMatcher as well which appears to be [supported in the espresso driver](https://github.com/appium/appium-espresso-driver/pull/516).
There is no ViewMatcher doc at all currently, though it seems to be supported in espresso driver, so not sure what C# docs would be helpful here.
Looking to add support for decorating some android views with automation identifiers that get set in `View.setTag(R.id.automation_id, "idvaluehere")` and using ViewMatchers to select views based on those values (ie: `onView(withTagKey(8675309,is('idvaluehere')))` with a selector such as:
```json
{
"name" : "withTagKey",
"args" : [ 
8675309, 
{ 
"name" : …
```
=> feat: Add support for Android Espresso's ViewMatcher

src/Appium.Net/Appium.Net.csproj
Project file
Reenabled the GeneratePackageOnBuild property because the release github action looks for a generated package for it to publish.
The file version is still removed so the assembly and package should not show an outdated version
=> build: reenable GeneratePackageOnBuild

src/Appium.Net/Appium/Service/AppiumCommandExecutor.cs
closes #403
- Added method to modify/add "X-Idempotency-Key" request header before the HTTP request to the remote server is made
- lint AppiumCommandExecutor …
=> feat: Add idempotency header to request for new sessions

src/Appium.Net/Appium/iOS/IOSCommandExecutionHelper.cs, src/Appium.Net/Appium/iOS/IOSDriver.cs, src/Appium.Net/Appium/iOS/Interfaces/IHasSettings.cs, test/integration/IOS/SettingTest.cs
Add the ability to get or update iOS driver settings.
=> Settings implementation for iOS driver

src/Appium.Net/Appium.Net.csproj, test/integration/Appium.Net.Integration.Tests.csproj
Target NET. Framework to 4.8 instead of 4.5 for both projects
Since .NET 4.8 is the recommended Framework by Microsoft we should progress from 4.5.
In addition, seems like Azure Pipeline-hosted VMS doesn't support .net4.5 any longer.
=> feat: Target .NET Framework 4.8 *v5*

src/Appium.Net/Appium/Enums/IOSMobileCapabilityType.cs
- Added `SimulatorStartupTimeout` capability to `IOSMobileCapabilityType`.
=> feat: Add `simulatorStartupTimeout` iOS capability

src/Appium.Net/Appium/Service/AppiumLocalService.cs, src/Appium.Net/Appium/Service/AppiumServiceConstants.cs, src/Appium.Net/Appium/Service/Options/GeneralOptionList.cs, test/integration/Properties/Resources.Designer.cs, test/integration/ServerTests/AppiumLocalServerLaunchingTest.cs
-Removed the usage of /wd/hub which is no longer in use starting from appium2.0 server
-Minor code improvements at AppiumLocalService.cs
-Removal of redundant 'using' in test/integration/Properties/Resources.Designer.cs
=> feat: Migrate AppiumLocalService to Appium 2

test/integration/Android/Device/NetworkTests.cs
Added Assert on currentConnectionType after we Toggle the Data
Dispose the Driver if it's not null
After toggling the data, better to check currentConnectionType was changed accordingly.
=> test: Add validations to 'CanToggleData' Test

.nuget/NuGet.targets
Starting with  VS2019, the recommended ToolVersion is 'Current'.
[vs2019 toolsVersion](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion?view=vs-2019)
=> feat: Switch Tools Version to 'Current'

test/integration/env.json.sample
Currently our 'env.json.sample' contains the 'dev' property as Lowercase while our code is looking for 'DEV' in uppercase.
https://github.com/appium/appium-dotnet-driver/blob/6434b152860a2cf3ff52e41b3c6522ebe31db646/test/integration/helpers/Env.cs#L47-L51 …
=> fix: dev property should be in uppercase inside the env.json.sample file

README.md
Currently the NuGet badge for beta version redirect for v4.4.0, instead of the latest beta version.
=> Fix: update broken link of 5.0.0-beta02 NuGet

README.md, src/Appium.Net/Appium.Net.csproj, test/integration/IOS/ClipboardTest.cs, test/integration/helpers/Apps.cs
In case we would like to rename the repo to match the other clients in the appium project, this is a good place to start.
As discussed with @akinsolb on slack …
=> refactor: Rename repository to dotnet-client

test/integration/Android/WaitTests.cs
Due to some issues opened on WebDriverWait Implimantion, I've added some tests for this aspect.
see issues:
- https://github.com/appium/appium-dotnet-driver/issues/457
- https://github.com/appium/appium-dotnet-driver/issues/225 …
=> test: Add WaitTests for WebDriverWait usage

test/integration/Windows/ImagesComparisonTest.cs
- Rename the class, since we have more than one test.
- Add AutomationName capability to support appium 2.x server
- Add LaunchApp() to improve stability on splash screen cases.
=> test: Fix Windows\ImagesComparisonTests

PULL_REQUEST_TEMPLATE.md
=> docs: Grammar fixes

README.md
- add install NuGet CLI step
- fix NuGet naming violations
- Update the set API key link
=> docs: Update the 'To Setup Nuget' section

README.md
The current link to NuGet.exe is broken, therefore I updated the link to use the latest working download link.
=> docs: Fix broken link for NuGet.exe

src/Appium.Net/Appium/AppiumDriver.cs, test/integration/Android/Device/AppTests.cs, test/integration/IOS/Device/AppTests.cs
Adding timeout to the activate app function
- [] New feature (non-breaking change which adds value to the project)
sometimes on slower emulators, activating the app requires more time then provided by default, this change solves it. …
=> feat: added the ability to activate the app with timeout

src/Appium.Net/Appium.Net.csproj, src/Appium.Net/Appium/Android/Enums/AndroidKeyCode.cs, src/Appium.Net/Appium/Enums/MobileCapabilityType.cs
Removed some warnings I saw on the build log. 
there are too many , but got to start somewhere :)
=> chore: Removing some warnings from build logs

src/Appium.Net/Appium.Net.csproj, test/integration/Android/Device/AppTests.cs
following commit https://github.com/appium/dotnet-client/commit/6294052fbe38e1a4f6bfdda61312326e397ed8e2 , AppTests can't pass since IntentApp was removed.
I made some adjustments and cleaned the obsolete strings 
=> test: Fix AppTests due to IntentApp removal

.github/workflows/release-nuget.yml, src/Appium.Net/Appium.Net.csproj
Updates the [GitHub nuget build and deploy action](https://github.com/appium/dotnet-client/actions/workflows/release-nuget.yml) to work with Semantic Version 2
resolves #578
=> chore: update nuget build and deploy github action to support semantic versioning 2.0

test/integration/Windows/ClickElementTest.cs
With the new appium 2.x server AutomationName is mandatory. 
=> fix: Add missing AutomationName option for ClickElementTest

README.md
It seems like some people are not aware of the changes made on the 5.x version that requires them to either update to appium server 2.x or add the base-path argument when starting the server.
=> docs: add Appium server compatibility for v5.x section 

test/integration/Android/Device/BrowserTests.cs
BrowserTests is missing the newly required option: AutomationName for appium 2.x server
add as well small validation to dispose driver just in case it's not null.
=> test: add missing AutomationName option

src/Appium.Net/Appium.Net.csproj, test/integration/IOS/ClipboardTest.cs, test/integration/helpers/Apps.cs
Apply the repo name change on the rel branch 
=> refactor: Rename repository to dotnet-client 

src/Appium.Net/Appium/AppiumCommand.cs, src/Appium.Net/Appium/AppiumDriver.cs, src/Appium.Net/Appium/AppiumDriverCommand.cs, src/Appium.Net/Appium/Windows/WindowsDriver.cs, test/integration/Android/ActivityTest.cs
As mentioned in https://github.com/appium/appium/issues/15807, these methods will not be supported anymore.
Related item:
https://github.com/appium/dotnet-client/issues/562
For now, I updated only one Integration test to use the more standard Appium session management, more will follow. …
=> chore: Deprecate legacy app management helpers

README.md
Due to many Questions/Issues related to the WinAppDriver, I decided to add a section to explain the current state and how some can run on Windows Applications.
also fixed some Typo/grammar mistakes along the way.
=> docs: Update README.md with WinAppDriver Notice[Rel/5.x]

src/Appium.Net/Appium/Android/AndroidCommandExecutionHelper.cs, src/Appium.Net/Appium/AppiumCommand.cs, src/Appium.Net/Appium/AppiumDriverCommand.cs, src/Appium.Net/Appium/AppiumElement.cs, src/Appium.Net/Appium/Tizen/TizenCommandExecutionHelper.cs, test/integration/Android/ElementTest.cs, test/integration/IOS/ElementTest.cs
- Added deprecations messages for SetImmediateValue & ReplaceValue methods
- Added Deprecated region for Input value in AppiumDriverCommand
- Cleanup SetImmediateValueTests for both iOS and Android
- Update ReplaceValueTest in Android to use 'mobile: replaceElementValue'
Since replaceValue & setValue sends "value", but since the original setValue API requires "text" in W3C we receive an error.
=> chore: add deprecations for SetImmediateValue & ReplaceValue methods

README.md
Add Build and Deploy NuGet badge + Change Nuget to use pre-release which is the only one relevant for 5.x branch
=> docs: Update NuGet badges  (Release 5.x)

src/Appium.Net/Appium/AppiumDriver.cs
the [directConnect PR](https://github.com/appium/dotnet-client/pull/627) has broken the functionality of set commandTimeout in 2 cases of appiumDriver class:
=> fix: use commandTimeout parameter instead of default value.

src/Appium.Net/Appium/AppiumElement.cs, test/integration/Android/ElementTest.cs
Add new methods for extended element finding and rename utility method in AppiumElement class
- Add `FindElement` method to return AppiumElement
- Add `FindElements` method to return ReadOnlyCollection<AppiumElement>
- Rename `ConvertToExtendedWebElementCollection` to `ConvertToAppiumElementCollection`
These methods and the renaming improve compatibility with AppiumElement types and enhance element-finding capabilities.
Closing https://github.com/appium/dotnet-client/issues/573
Please provide more details about changes if it is necessary. If there are new features you can provide code samples showing how they work and possible use cases. Also, you can create …
=> fix: Add new methods for extended element finding in AppiumElement

test/integration/IOS/AlertTests.cs
- ByIosUIAutomation  selector is obsolete, before I remove it completely I prefer to fix current tests 
- added a new test for alerts along the way 
=> test: remove obsolete ByIosUIAutomation and add new test in ios/AlertTests

test/integration/helpers/Apps.cs
When trying to use tree/master in the apps path we get an error related to zip file
once switching to blob/main all seems to work fine
- [x Have you provided integration tests to pass against the beta version of appium? (for Bugfix or New feature) …
=> fix: use blob/main instead of tree/master for apps urls

src/Appium.Net/Appium/Enums/IOSMobileCapabilityType.cs
Updated the docs link to use the new docs page of ios caps
=> chore: update iOS-specific capabilities docs hyperlink

.gitignore
Added .DS_Store files to `.gitignore` which are generated on MacOS.
The .DS_Store file is used to store Finder information about that folder, so it's having no use in a git repo. 
=> chore: Add .DS_Store to .gitignore

.github/dependabot.yml
Until Someone decides to fix the issue: https://github.com/dependabot/dependabot-core/issues/8177
I think it's best to change the interval of `test/integration` updates to `monthly` so we will have less noise and clutter on the PR section. …
=> github: Update /test/integration interval to monthly

README.md
the NuGet badge was missing a proper link
=> docs: Add link to NuGet version

src/Appium.Net/Appium/AppiumOptions.cs
No major changes, just fixed some small wording issues
Please refer to file diff
=> chore: Update AppiumOptions.cs: Fix typos

test/integration/Android/ActionsChainsTest.cs
Added Tests for W3C Actions, afterward we can remove the entire deprecated touch classes.
related to https://github.com/appium/dotnet-client/issues/712
@laolubenson, Maybe the test class name can be improved, WDYT?
another point to consider is how we are going to handle the ambiguous issue users will probably face.
```
using static OpenQA.Selenium.Interactions.PointerInputDevice;
using PointerInputDevice = OpenQA.Selenium.Appium.Interactions.PointerInputDevice;
```
Please provide more details about changes if it is necessary. If there are new features you can provide code samples showing how they work and possible use cases. Also, you can create [gists](https://gist.github.com) …
=> test: Add tests for W3C Actions

test/integration/IOS/ClipboardTest.cs
Removal of ios clipboard test which use System.Drawing.Common
System.Drawing.Common is only supported on windows platforms. 
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only …
=> test: remove test using System.Drawing.Common

test/integration/Windows/MultiSelectControlTest.cs
- assert fixes
- use proper members for methods
- better cleanup at teardown
=> chore: fixes and code improvements on Windows MultiSelectControlTest

src/Appium.Net/Appium.Net.csproj, src/Appium.Net/Appium/Service/AppiumLocalService.cs, test/integration/Android/ClipboardTest.cs, test/integration/Appium.Net.Integration.Tests.csproj
I've been contacted by numerous people saying the fact we dropped the support for .NET Framework 4.8 has blocked them from upgrading to latest RC versions
With this PR we should be able to have backward compatability with the Net48  …
=> refactor: reintroduce the .NET Framework 4.8 target framework

src/Appium.Net/Appium/MobileBy.cs
XML comments fixes.
inspired by https://github.com/appium/dotnet-client/issues/733
=> chore: Fix XML comments in MobileBy.cs

src/Appium.Net/Appium/Android/AndroidDriver.cs, src/Appium.Net/Appium/Mac/MacDriver.cs, src/Appium.Net/Appium/iOS/IOSDriver.cs
Update parameter names and remove deprecated wd/hub from Uri examples 
=> docs: Update XML comments for various drivers classes

src/Appium.Net/Appium/AppiumCommand.cs, src/Appium.Net/Appium/AppiumDriver.cs, src/Appium.Net/Appium/AppiumDriverCommand.cs, src/Appium.Net/Appium/Interfaces/IInteractsWithApps.cs, src/Appium.Net/Appium/Windows/WindowsDriver.cs, src/Appium.Net/Appium/Windows/WindowsDriverCommand.cs, test/integration/Android/SettingTest.cs, test/integration/Android/WaitTests.cs, test/integration/ServerTests/StartingAppLocallyTest.cs, test/integration/Windows/ClickElementTest.cs, test/integration/Windows/ImagesComparisonTest.cs
Remove `CloseApp` from AppiumDriverCommand and move it to WindowsDriverCommand since we have no other option for the time being. (TerminateApp is not implemented on the WinAppDriver side)
Replaced all usages of `CloseApp` with `TerminateApp` in the Integration Tests
Please provide more details about changes if necessary. If there are new features, you can provide code samples showing how they work and possible use cases. Also, you can create [gists](https://gist.github.com) with pasted C# code samples or put them here using markdown.  …
=> chore: Removal of obsolete CloseApp

src/Appium.Net/Appium/Android/AndroidCommandExecutionHelper.cs, src/Appium.Net/Appium/AppiumCommand.cs, src/Appium.Net/Appium/AppiumDriverCommand.cs, src/Appium.Net/Appium/AppiumElement.cs, src/Appium.Net/Appium/Tizen/TizenCommandExecutionHelper.cs
Removal of deprecated Input value endpoints
=> chore: Removal of deprecated Input value endpoints

src/Appium.Net/Appium/AppiumCommand.cs, src/Appium.Net/Appium/Interfaces/IHidesKeyboard.cs, src/Appium.Net/Appium/Interfaces/IHidesKeyboardWithKeyName.cs
=> fix: XML docs fixes

.github/release-drafter.yml
Since we are now officially on v5 on the latest version, no need for release-drafter to publish prerelease versions  
=> github: Set prerelease flag to `false` in release-drafter.yml

test/integration/IOS/ElementTest.cs
- Remove the Deprecated  IosUiAutomation Test
- Add 2 new tests for ClassName 
=> test: Fix ios ElementTests

src/Appium.Net/Appium.Net.csproj, src/Appium.Net/Appium/AppiumDriver.cs, src/Appium.Net/Appium/Service/AppiumCommandExecutor.cs
This bumps to Selenium 4.23 and fixes the build errors in AppiumDriver and AppiumCommandExecutor to flow through the new ExecuteAsync() methods in Selenium 4.23+.  Fixes #798 
=> break: ExecuteAsync() under the hood implementation after bumping to Selenium 4.23

README.md
- Added compatibility information for Appium .NET Client versions 5.1.0, v5, and v4.
- Specified corresponding Selenium .NET binding versions and .NET versions.
- Included a note about the dependency on Selenium .NET binding and its potential impact on the Appium .NET Client. …
=> docs: Add compatibility matrix for Appium .NET Client

src/Appium.Net/Appium/AppiumDriver.cs
Override and increase the default HTTP requests command timeout from 1 minute to 10 minutes.
=> feat: Override selenium default command timeout

.github/release-drafter.yml
Add new category titled "📚 Documentation" for PRs labeled with Docs in release.drafter
=> github: Add Documentation category in release-drafter.yml

README.md
All deprecated methods are already long gone, and an active PR is also in place for TouchActions.
now it's a good time to remove that section.
=> docs: Remove the Deprecated Methods section

test/integration/Appium.Net.Integration.Tests.csproj, test/integration/helpers/Env.cs
- The selenium dotnet client recently moved to the `System.Text.Json` package. Why shouldn't we? :)
- Replace `Newtonsoft.Json` with `System.Text.Json`
- Added error handling for JSON deserialization and fallback logic for environment variables. …
=> build(deps): Migration from `Newtonsoft.Json` to `System.Text.Json` package

.github/PULL_REQUEST_TEMPLATE.md
=> github: update PR template to support test fixes

src/Appium.Net/Appium.Net.csproj, src/Appium.Net/Appium/Service/AppiumLocalService.cs
Currently Appium targets to support:
- net6.0
- net framework 4.8
It means that I cannot use Appium with .net framework 4.7
Use `netstandard2.0` to cover more frameworks.
https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#when-to-target-net80-vs-netstandard
> For existing code that targets .NET Standard 2.0 or later, there's no need to change the TFM to net8.0 or a later TFM. The only reason to retarget from .NET Standard to .NET 8+ would be to gain access to more runtime features, language features, or APIs.
Please provide more details about changes if necessary. You can provide code samples showing how they work and possible use cases if there are new features. Also, you can create [gists](https://gist.github.com) with pasted C# code samples or put them …
=> refactor: Use `netstandard2.0` as target framework to support wider frameworks

README.md
=> docs: Update the Dependencies section

.github/release-drafter.yml
- Apparently, NEW_CONTRIBUTORS is not supported(yet), so rolled back those changes.
- Added missing emojis per category
- better readability for contributors' template
=> fix: Revert changes for NEW_CONTRIBUTORS

.github/dependabot.yml
Remove the selenium group (since there is only one package) and update the test/integration schedule to a weekly
=> github: Remove the selenium group

.github/dependabot.yml, src/Appium.Net/Appium/Android/AndroidCommandExecutionHelper.cs, src/Appium.Net/Appium/Android/AndroidDriver.cs, test/integration/Android/LockDeviceTest.cs
- Replaced deprecated JSONWP commands with `mobile: lock`, `mobile: isLocked`, and `mobile: unlock` extensions.
- Updated the `Lock` method to accept an optional `seconds` parameter for auto-unlock functionality.
- Updated the `Unlock` method to support required `key` and `type` parameters, with optional `strategy` and `timeoutMs` arguments.
- Improved code robustness with null checks and parameter validation.
Please provide more details about changes if necessary. You can provide code samples showing how they work and possible use cases if there are new features. Also, you can create [gists](https://gist.github.com) with pasted C# code samples or put them here using markdown. …
=> BREAKING CHANGE: `AndroidDriver` to use modern `mobile:` commands for Lock, IsLocked and Unlock

azure-pipelines.yml
Recently the CI tests were falling too often, I suspect it might be because both framework tests ran in parallel. This PR will ensure they run one after the other to avoid conflicts.
=> ci: Split tests into two separate tasks per framework

test/integration/Android/Session/LogTests.cs
When getting bugreport logs, there is more than one entry.
can`t recall how it used to be.
@laolubenson / @KazuCocoa Maybe you guys recall if it's normal behavier:
=> test: fix assertion for logs entry

test/integration/IOS/ScrollingSearchingTest.cs
update scrolling tests to use modern mobile commands for visibility checks
=> test: Replace deprecated `ByIosUIAutomation` in ScrollingSearchingTest

test/integration/IOS/ClipboardTest.cs
update ClipboardTest to use OneTimeSetUp and OneTimeTearDown, disable full reset
=> test: Disable `FullReset` in IOS/ClipboardTest

RELEASE_NOTES.md
=> docs: Update RELEASE_NOTES.md

test/integration/Android/Device/NetworkTests.cs
replace AppiumDriver with AndroidDriver in NetworkTests and simplify method calls
=> test: NetworkTests Improvements

src/Appium.Net/Appium/Android/Interfaces/IPushesFiles.cs, src/Appium.Net/Appium/Interfaces/IFindsByFluentSelector.cs, src/Appium.Net/Appium/Interfaces/IInteractsWithApps.cs, src/Appium.Net/Appium/Interfaces/INetworkActions.cs, src/Appium.Net/Appium/Interfaces/ITouchAction.cs
Refactored parameter names across multiple interfaces for clarity:
- `IPushesFiles.PushFile`: `base64Data` to `stringData` and `file`
- `IFindsByFluentSelector.FindElements`: `by` to `selector`
- `IInteractsWithApps`: `appPath` to `bundleId` and `appId`
- `ITouchAction.LongPress`: `el` to `element`
Updated documentation comments for better compatibility:
- `INetworkActions.ToggleData`: `<=` to `&lt;=`
- Removed empty `<param>` tag in `INetworkActions.SetGsmSignalStrength`
Please provide more details about changes if necessary. You can provide code samples showing how they work and possible use cases if …
=> fix: Refactor parameter names and update documentation

test/integration/Android/FiltersTests.cs
Introduced a new test class `FiltersTests` in the `Appium.Net.Integration.Tests.helpers` namespace. The class is decorated with the `[TestFixture]` attribute and includes the following methods:
- `BeforeAll()`: Initializes the `AndroidDriver` and sets the implicit wait timeout.
- `SetUp()`: Starts the "ApiDemos" activity before each test.
- `FirstWithName_ReturnsCorrectElement()`: Verifies that `Filters.FirstWithName` returns the correct element.
- `AfterAll()`: Quits the `AndroidDriver` and stops the local Appium service if the server is not remote.
Necessary namespaces for NUnit, Selenium, and Appium are imported.
_Put an `x` in the boxes …
=> test: Add FiltersTests class with NUnit tests for Filters.FirstWithName

test/integration/Appium.Net.Integration.Tests.csproj
The project file `Appium.Net.Integration.Tests.csproj` has been modified to update the target frameworks. The project was previously targeting .NET Framework 4.8 and .NET 6.0. The change replaces .NET 6.0 with .NET 8.0, so the project now targets .NET Framework 4.8 and .NET 8.0. This update likely reflects a move to support the latest version of .NET.
About markdown please read [Mastering …
=> refactor: Update the Integration project target frameworks to .NET 8.0

test/integration/helpers/Env.cs
Reordered the Init method to check _initialized flag at the start, ensuring early return if already initialized. Moved _env dictionary initialization before the check to guarantee setup before any operations. Removed _initialized flag setting and env.json reading from the try block, simplifying the initialization logic.
About markdown please read [Mastering …
=> fix: Init method in Env.cs for better initialization

test/integration/ServerTests/DirectConnectTest.cs
OpenQA.Selenium.Response class will be deprecated in selenium 4.30
I've updated the code under `test/integration/ServerTests/DirectConnectTest.cs ` to follow the New Response ctor.
Refactored `DirectConnectTest` class to improve code readability and consistency. Updated test methods to use modern C# features such as inline variable declarations, collection initializers, and object initializers. Added a new test method `WithMissingDirectConnectHost` to cover the missing `directConnectHost` scenario.
Please provide more details about changes if necessary. You can provide code samples showing how they work …
=> test: Refactor DirectConnectTest for readability and consistency

src/Appium.Net/Appium/AppiumCommandExecutionHelper.cs
Fixes https://github.com/appium/dotnet-client/issues/916
ToLower/ToUpper reflects the host language config, so we must use ToLowerInvariant/ToUpperInvariant to avoid the issue
=> fix: use ToLowerInvariant in clipboard to follow invariant culture

src/Appium.Net/Appium/Service/AppiumClientConfig.cs, src/Appium.Net/Appium/Service/AppiumCommandExecutor.cs, src/Appium.Net/Appium/Service/AppiumHttpCommandExecutor.cs, test/integration/ServerTests/AppiumClientConfigTest.cs, test/integration/ServerTests/RelaxSslValidationTest.cs
This pull request introduces several changes to the Appium .NET client to enhance SSL validation handling and refactor the command executor. The most important changes include adding a new configuration option for relaxing SSL validation, creating a new `AppiumHttpCommandExecutor` class, and updating the command executor to use this new class.
Enhancements to SSL validation handling:
* [`src/Appium.Net/Appium/Service/AppiumClientConfig.cs`](diffhunk://#diff-acaea4c69fa349e14ac6ef66a5d18086bf6ca73b3c438f9dc526776b5320974cR40-R42): Added a new property `RelaxSslValidation` to the `AppiumClientConfig` class.
* [`src/Appium.Net/Appium/Service/AppiumHttpCommandExecutor.cs`](diffhunk://#diff-2927dcf8feb462c01738248d5dde7e1a242888904a186155f93530561979f77bR1-R49): Created a new …
=> feat: Add support for Relax SSL validation

src/Appium.Net/Appium.Net.csproj, test/integration/Android/BiDiTests.cs, test/integration/helpers/Caps.cs
https://github.com/appium/dotnet-client/issues/953
This PR adds Bidi tests in dotnet to check if it can call Bidi stuff via the selenium deps.
=> chore: add bidi test with newser selenium webdriver dependency
