appium/dotnet-client

appium-dotnet-driver/Appium/AppiumDriver.cs
appium-dotnet-driver/Appium/AppiumDriverCommand.cs
appium-dotnet-driver/Appium/Location.cs
appium-dotnet-driver/appium-dotnet-driver.csproj

set location of device

---

appium-dotnet-driver/Appium/Android/AndroidDriver.cs
appium-dotnet-driver/Appium/Android/Enums/ConnectionType.cs
appium-dotnet-driver/Appium/AppiumDriver.cs
appium-dotnet-driver/Appium/Interfaces/IScrollsTo.cs
appium-dotnet-driver/Appium/iOS/IOSDriver.cs
appium-dotnet-driver/Appium/iOS/IOSElement.cs
appium-dotnet-driver/appium-dotnet-driver.csproj
appium-dotnet-driver/packages.config
samples/AndroidGestureTest.cs
samples/packages.config
samples/samples.csproj

The conflict resolving

---

RELEASE_NOTES.md
appium-dotnet-driver/Appium/MultiAction/MultiAction.cs
appium-dotnet-driver/Appium/MultiAction/TouchAction.cs
appium-dotnet-driver/Properties/AssemblyInfo.cs
appium-dotnet-driver/appium-dotnet-driver.nuspec
samples/AndroidSimpleTest.cs
samples/PageObjectTests/Other/AndroidJSWebViewTest.cs
samples/PageObjectTests/Other/AndroidTouchActionTest.cs
samples/PageObjects/AndroidJavaScriptTestPageObject.cs
samples/PageObjects/AndroidPageObjectThatChecksTouchActions.cs
samples/samples.csproj

the bug which prevented the using of TouchAction/MultiTouchActions with
IWebElement was fixed
#103

#103 bug fix

---

appium-dotnet-driver/Appium/Enums/MobilePlatform.cs
appium-dotnet-driver/Appium/Interfaces/IFindByWindowsUIAutomation.cs
appium-dotnet-driver/Appium/Windows/Enums/WindowsKeyCodes.cs
appium-dotnet-driver/Appium/Windows/WindowsDriver.cs
appium-dotnet-driver/Appium/Windows/WindowsElement.cs
appium-dotnet-driver/appium-dotnet-driver.csproj
integration_tests/Windows/WindowsClickElementTest.cs
integration_tests/Windows/WindowsMultiSelectControlTest.cs
integration_tests/integration_tests.csproj

...just the conflict resolving

Jonstoneman feature/win

---

appium-dotnet-driver/Appium/AppiumCommand.cs
appium-dotnet-driver/Appium/AppiumDriverCommand.cs

Added 'appium/simulator/touch_id' endpoint to AppiumCommands.cs
##Details
Touch ID is a feature in Apple products (see https://support.apple.com/en-ca/HT201371). This endpoint simulates the behaviour.

Added 'touch_id' endpoint

---

appium-dotnet-driver/Appium/AppiumCommand.cs
appium-dotnet-driver/Appium/iOS/IOSCommandExecutionHelper.cs
appium-dotnet-driver/Appium/iOS/IOSDriver.cs
appium-dotnet-driver/Appium/iOS/Interfaces/IPerformsTouchID.cs

Adding ToggleTouchIdEnrollment to IOSDriver
- [* ] New feature (non-breaking change which adds functionality)

Exposing ToggleTouchIdEnrollment through IOSDriver

---

appium-dotnet-driver/Properties/AssemblyInfo.cs
appium-dotnet-driver/appium-dotnet-driver.nuspec

Build number was changed to 4.0.0.BETA1. 
The starting of 4.x seria.

4.0.0.BETA1. Build number.

---

appium-dotnet-driver/appium-dotnet-driver.nuspec

nuspec was updated

---

RELEASE_NOTES.md
appium-dotnet-driver/Properties/AssemblyInfo.cs
appium-dotnet-driver/appium-dotnet-driver.nuspec

nuspec was updated/improved

---

appium-dotnet-driver/Appium/Enums/MobilePlatform.cs
appium-dotnet-driver/Appium/Tizen/TizenCommandExecutionHelper.cs
appium-dotnet-driver/Appium/Tizen/TizenDriver.cs
appium-dotnet-driver/Appium/Tizen/TizenElement.cs
appium-dotnet-driver/appium-dotnet-driver.csproj

Added Tizen Driver to support Appium in Tizen.
This PR is to support Appium on the Tizen Platform.

Add Tizen Driver

---

appium-dotnet-driver/Appium/Tizen/TizenDriver.cs
appium-dotnet-driver/Appium/Tizen/TizenElementFactory.cs
appium-dotnet-driver/appium-dotnet-driver.csproj

+TizenElementFactory.cs
Change to TizenDriver.cs
Implemented element factory for TizenDriver class in order to complete the implementation of #236, by adding missing abstract members to TizenDriver.cs. Without this commit the source will not build successfully.

implement TizenElementFactory class 

---

appium-dotnet-driver/Appium/Enums/MobileSelector.cs
appium-dotnet-driver/Appium/Interfaces/IFindByTizenUIAutomation.cs
appium-dotnet-driver/Appium/MobileBy.cs
appium-dotnet-driver/Appium/Tizen/TizenDriver.cs
appium-dotnet-driver/Appium/Tizen/TizenElement.cs
appium-dotnet-driver/appium-dotnet-driver.csproj

This PR adds `IFindByTizenUIAutomation` interface and make both `TizenDriver` and `TizenElement` implement it.
This is what makes `TizenDriver`/`TizenElement` the same as other platforms such as android, iOS and Windows.

Adds IFindByTizenUIAutomation interface

---

appium-dotnet-driver/appium-dotnet-driver.csproj
appium-dotnet-driver/packages.config
integration_tests/integration_tests.csproj
integration_tests/packages.config

appium-dotnet-driver.csproj
integration_tests.csproj
appium-dotnet-driver/packages.config
integration_tests/packages.config
Added Microsoft.CodeAnalysis.FxCopAnalyzers nuget package to enforce code analysis on src and test projects, addressing #248

Add Roslyn Analysers

---

appium-dotnet-driver/Appium/AppiumWebElement.cs

AppiumWebElement.cs
Corrected the IsElementDisplayed endpoint override for Appium driver related elements. resolves #263

fix for #263 to override Selenium Displayed endpoint call

---

appium-dotnet-driver/Appium/Enums/AndroidMobileCapabilityType.cs
appium-dotnet-driver/Appium/Enums/AutomationName.cs
appium-dotnet-driver/Appium/PageObjects/Attributes/FindsBySelendroidAttribute.cs
appium-dotnet-driver/Appium/PageObjects/Attributes/MobileFindsByAllAttribute.cs
appium-dotnet-driver/Appium/PageObjects/Attributes/MobileFindsBySequenceAttribute.cs
appium-dotnet-driver/Appium/Service/Options/AndroidOptionList.cs

Objects relating to Selendroid
Annotations
Marked Selendroid objects obsolete

Mark Selendroid as obsolete

---

appium-dotnet-driver/appium-dotnet-driver.csproj

Update package release notes for 4.0.0.4-beta release

---

appium-dotnet-driver/Appium/Android/AndroidStartScreenRecordingOptions.cs
appium-dotnet-driver/Appium/Android/AndroidStopScreenRecordingOptions.cs
appium-dotnet-driver/Appium/AppiumCommand.cs
appium-dotnet-driver/Appium/AppiumDriver.cs
appium-dotnet-driver/Appium/AppiumDriverCommand.cs
appium-dotnet-driver/Appium/Interfaces/IScreenRecordingOptions.cs
appium-dotnet-driver/Appium/ScreenRecording/BaseScreenRecordingOptions.cs
appium-dotnet-driver/Appium/ScreenRecording/BaseStartScreenRecordingOptions.cs
appium-dotnet-driver/Appium/ScreenRecording/BaseStopScreenRecordingOptions.cs
appium-dotnet-driver/Appium/ScreenRecording/ScreenRecordingUploadOptions.cs
appium-dotnet-driver/Appium/iOS/IOSStartScreenRecordingOptions.cs
appium-dotnet-driver/Appium/iOS/IOSStopScreenRecordingOptions.cs
integration_tests/Android/AndroidScreenRecordingTest.cs
integration_tests/helpers/Caps.cs
integration_tests/iOS/IOSScreenRecordingTest.cs

Screen recording implemented

---

src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/PageObjects/AppiumPageObjectMemberDecorator.cs
src/Appium.Net/Appium/PageObjects/Attributes/FindsByWindowsAutomationAttribute.cs
src/Appium.Net/Appium/PageObjects/Attributes/MobileFindsByAllAttribute.cs
src/Appium.Net/Appium/PageObjects/Attributes/MobileFindsBySequenceAttribute.cs
src/Appium.Net/Appium/PageObjects/ByFactory.cs
src/Appium.Net/Appium/Windows/WindowsDriver.cs
test/integration/PageObjectTests/Windows/WindowsAlarmAppTest.cs
test/integration/PageObjects/WindowsAlarmApp.cs
test/integration/Windows/ClickElementTest.cs
test/integration/Windows/MultiSelectControlTest.cs

Add support for FindsByWindowsAutomationAttribute - see https://github.com/appium/appium-dotnet-driver/issues/237 for more details.
P.S - The name of the branch is a bit misleading since I've rebased it against master (4.0.0.0 beta 4).

Add support for FindsByWindowsAutomationAttribute

---

README.md

I had success with using Rider to update the client on my Mac and thought I'd share it with everyone else.

docs: JetBrains Rider instructions

---

src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
src/Appium.Net/Appium/Enums/AppState.cs
src/Appium.Net/Appium/Interfaces/IInteractsWithApps.cs

Added GetAppState.
Added GetAppState-Command (http://appium.io/docs/en/commands/device/app/app-state/).

Add Support for GetAppState Command

---

src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
src/Appium.Net/Appium/Interfaces/IInteractsWithApps.cs

Add support for TerminateApp
Added Terminate-App-Command (http://appium.io/docs/en/commands/device/app/terminate-app/).

Add Terminate App

---

CHANGELOG.MD
src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
src/Appium.Net/Appium/ImageComparison/ComparisonMode.cs
src/Appium.Net/Appium/ImageComparison/ComparisonOptions.cs
src/Appium.Net/Appium/ImageComparison/ComparisonResult.cs
src/Appium.Net/Appium/ImageComparison/FeaturesMatchingOptions.cs
src/Appium.Net/Appium/ImageComparison/FeaturesMatchingResult.cs
src/Appium.Net/Appium/ImageComparison/OccurenceMatchingOptions.cs
src/Appium.Net/Appium/ImageComparison/OccurenceMatchingResult.cs
src/Appium.Net/Appium/ImageComparison/SimilarityMatchingOptions.cs
src/Appium.Net/Appium/ImageComparison/SimilarityMatchingResult.cs
test/integration/Windows/ImagesComparisonTest.cs

New version of #354 
Based on appium/appium-base-driver#203
Add access to Appiums image comparison Apis (similar to appium/java-client#870)

Add Image comparison helpers 

---

CHANGELOG.MD
src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
src/Appium.Net/Appium/Interfaces/IInteractsWithApps.cs

Add Activate app

---

README.md

Update URL on badge since current badge URL is just for images.
None

Update URL on badges

---

.travis.yml
src/Appium.Net.sln

Deleted Travis CI config so that only Azure DevOps is used

Remove Travis CI config

---

CHANGELOG.MD
src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumCommandExecutionHelper.cs
src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
src/Appium.Net/Appium/Interfaces/IHidesKeyboard.cs

- Add IsKeyboardShown to IHidesKeyboard interface
- Add IsKeyboardShown command constant
- Implement IsKeyboardShown on Executor
- Implement IsKeyboardShown on Driver
Adds IsKeyboardShown functionality based on Appium protocol

feat: IsKeyboardShown

---

CHANGELOG.MD

fix: Add DataMatcher to changelog

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Add release drafter action
Creates and updated draft releases automatically when changes are merged to master

chore: Add release drafter

---

.github/release-drafter.yml

Update to the release-drafter to pick define version based on existing labels
Additions to #418

chore: resolve draft release version based on existing labels

---

.github/workflows/main.yml

Add more indentation to resolve parsing failure of github action yml.

chore: resolve pr labeler indentation issue

---

src/Appium.Net/Appium/Android/AndroidCommandExecutionHelper.cs
src/Appium.Net/Appium/Android/AndroidDriver.cs
src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumCommandExecutionHelper.cs
src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/Interfaces/INetworkActions.cs
test/integration/Android/Device/AuthenticationTest.cs
test/integration/Android/Device/NetworkTests.cs

Add support for toggling Airplane mode on Android

feat: add Toggle Airplane Mode & INetworkActions Interface

---

src/Appium.Net/Appium/Android/AndroidCommandExecutionHelper.cs
src/Appium.Net/Appium/Android/AndroidDriver.cs
src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/Interfaces/INetworkActions.cs
test/integration/Android/Device/NetworkTests.cs

Add support for toggling Wifi on Android.

feat: Toggle Wifi

---

src/Appium.Net/Appium/Android/AndroidCommandExecutionHelper.cs
src/Appium.Net/Appium/Android/AndroidDriver.cs
src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
src/Appium.Net/Appium/Enums/GsmCallActions.cs
src/Appium.Net/Appium/Interfaces/INetworkActions.cs
test/integration/Android/Device/NetworkTests.cs

closes #366
Add API for making GSM calls on emulator 

feat: Make GSM Call (Emulator Only)

---

src/Appium.Net/Appium/Android/AndroidCommandExecutionHelper.cs
src/Appium.Net/Appium/Android/AndroidDriver.cs
src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
src/Appium.Net/Appium/Enums/GsmSignalStrength.cs
src/Appium.Net/Appium/Interfaces/INetworkActions.cs
test/integration/Android/Device/NetworkTests.cs

closes #367
Add Android API for GSM Signal (Emulator only) command 

feat: Set Gsm Signal Strength

---

src/Appium.Net/Appium/Android/AndroidCommandExecutionHelper.cs
src/Appium.Net/Appium/Android/AndroidDriver.cs
src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
src/Appium.Net/Appium/Enums/GsmVoiceState.cs
src/Appium.Net/Appium/Interfaces/INetworkActions.cs
test/integration/Android/Device/NetworkTests.cs

Add API for GSM Voice endpoint
closes #368 

feat: GSM Voice State 

---

src/Appium.Net/Appium/Android/AndroidCommandExecutionHelper.cs
src/Appium.Net/Appium/Android/AndroidDriver.cs
src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
test/integration/Android/Device/SystemTests.cs

closes #362 & #363
Add API for System bars and Get Display Density

feat: System Bars & Display Density

---

src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/Enums/MobileSelector.cs
src/Appium.Net/Appium/Interfaces/IFindsByimage.cs
src/Appium.Net/Appium/MobileBy.cs

Add support for "-image" locator type
closes #250 

feat: Add image locator type 

---

src/Appium.Net/Appium.Net.csproj

Bump assembly version to 4.2.0 for next release

build: bump version to 4.2.0

---

.gitignore
src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/Interfaces/IFindsByimage.cs

fix: StackOverflowException when calling FindElementByImage()

---

src/Appium.Net/Appium.Net.csproj
src/Appium.Net/Appium.Net.xml

Create XML documentation file on "Release" build and copy it to both binary output directories.
This is related to issue #441.
Nevertheless I'm not sure, if there is something else needed to get this XML file into the nuget package. (maybe a nuget config file entry?)

build: Create XML documentation file on "Release" build (#441)

---

src/Appium.Net/Appium.Net.csproj
src/Appium.Net/Appium/AppiumDriverCommand.cs
test/integration/Android/EmulatorDeviceTime.cs

closes #440
- Replaced incorrect driver command for system time endpoint
- Removed binary file name from project as github actions provides this for nuget
- Disabled automatic nuget package creation on local build

fix: device system time null exception

---

src/Appium.Net/Appium/Service/Options/GeneralOptionList.cs

Add relaxed-security option
Add relaxed-security option for AppiumServiceBuilder
- [ x] New feature (non-breaking change which adds functionality)

feat: Updated GeneralOptionList.cs by adding relaxed-security option for AppiumServiceBuilder

---

README.md

The current sample link redirects to an old repo, instead of the current one.

chore: Update Sample link

---

azure-pipelines.yml

Update vmImage to window's latest

fix: Update azure-pipelines.yml

---

test/integration/README.md

Clearer Instructions for running Integrations tests in the remote appium server section

docs: Update remote Appium server section

---

CHANGELOG.MD

we were missing changelogs for version 5. 
[issue 48](https://github.com/appium/appium-dotnet-driver/issues/485)

Add ChangeLogs for 5.x.x

---

src/Appium.Net/Appium/AppiumElement.cs
test/integration/Android/ElementTest.cs

Implement the ReplaceValue method for AppiumElement.

feat: Add ReplaceValue method

---

test/integration/Android/ActivityTest.cs

fix Contacts activity tests. 
Since the Contacts activity in use was deprecated and replaced with a new activity name, an update was required. 

test: Fix Contacts activity

---

src/Appium.Net/Appium.Net.csproj

-Bump Selenium NuGets from 4.4.0 to 4.5.1
-Update Copyright year
- [] New feature (non-breaking change which adds functionality)

build(deps): bump Selenium from 4.4.0 to 4.5.1

---

README.md

Since it seems to be confusion among users about which version they should use, a note message can do only good.

docs: Add Note message to README

---

README.md

fix: Typo fix on Readme.md

---

README.md

Update the latest stable version in the note section

docs: Update stable version in Readme file

---

RELEASE_NOTES.md

Added the latest versions (4.4.0 & 5.0.0-beta2)

docs: Update RELEASE_NOTES.md with latest versions (4.4.0 & 5.0.0-beta2)

---

test/integration/Appium.Net.Integration.Tests.csproj

Bump NUnit3TestAdapter from 4.2.1 to 4.3.0

build(deps): Bump NUnit3TestAdapter from 4.2.1 to 4.3.0

---

src/Appium.Net/Appium.Net.csproj

Bump SourceLink.GitHub from 1.0.0 to 1.1.1

build(deps): Bump SourceLink.GitHub from 1.0.0 to 1.1.1

---

test/integration/Android/Device/SystemTests.cs

Following issue: https://github.com/appium/appium-dotnet-driver/issues/497, I saw it would be appropriate to add a test for open notifications.

test: Add OpenNotifications test

---

src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs

I've Missed two more regions while pushing https://github.com/appium/appium-dotnet-driver/pull/548

chore: add deprecations for PerformTouchAction and PerformMultiAction v2

---

azure-pipelines.yml

Following https://github.com/appium/dotnet-client/issues/249 
Execute unit tests as a part of CI process

ci: Add 1st NUnit Test to pipeline *master*

---

test/integration/Appium.Net.Integration.Tests.csproj

bump Microsoft.NET.Test.Sdk to 17.4.0 in /test/integration

build(deps): Update Microsoft.NET.Test.Sdk to 17.4.0 in /test/integration

---

src/Appium.Net/Appium.Net.csproj

Update Language Version to 8.0 on Appium.Net.csproj
In order to support default interface implementations, we need to update the project to use langVersion 8.0

feat: Update language version to 8.0 on Appium.Net.csproj

---

test/integration/Android/ActivityTest.cs
test/integration/Android/ClipboardTest.cs
test/integration/Android/CurrentPackageTest.cs
test/integration/Android/Device/AuthenticationTest.cs
test/integration/Android/Device/HideKeyboardTestCase.cs
test/integration/Android/Device/NetworkTests.cs
test/integration/IOS/AppStringsTest.cs
test/integration/IOS/ClipboardTest.cs
test/integration/IOS/Device/AppTests.cs
test/integration/IOS/LockDeviceTest.cs

Removal of some unused namespaces from some Integration tests classes
- [] Have you provided integration tests to pass against the beta version of appium? (for Bugfix or New feature)

chore: Remove and sort usings from Integration tests

---

README.md

It seems like some people are not aware of the changes made on the 5.x version that requires them to either update to appium server 2.x or add the base-path argument when starting the server.

Docs: Add Appium server compatibility for v5.x section [Release]

---

test/integration/Windows/ClickElementTest.cs

Removal of Redundant cast in [ClickElementTest.cs](https://github.com/appium/dotnet-client/compare/release/5.0.0...Dor-bl:winTests?expand=1#diff-db18e44d71ee2db37acaed370024920a8b2cd142bcebc95d7266bed4e1be7a4d)

test: Remove redundant cast

---

test/integration/Windows/StickyNotesTest.cs

Add missing AutomationName option to StickyNotesTest for Appium 2.x Support
- [] New feature (non-breaking change which adds value to the project)

test: add missing AutomationName option to StickyNotesTest

---

src/Appium.Net/Appium.Net.csproj

Bumps System.Drawing.Common from 4.5.1 to 7.0.0 in /src/Appium.Net

build(deps): bump System.Drawing.Common from 4.5.1 to 7.0.0

---

README.md

Add deploy NuGet package badge

docs: Add deploy NuGet package badge

---

NOTICE

Update the current year in the NOTICE file 

Docs: Update NOTICE

---

NOTICE

update the current year in the NOTICE file 

docs: Update NOTICE [Rel5.x]

---

README.md

Due to many Questions/Issues related to the WinAppDriver, I decided to add a section to explain the current state and how some can run on Windows Applications.
also fixed some Typo/grammar mistakes along the way.

Update README.md with WinAppDriver Notice

---

test/integration/ServerTests/AppiumLocalServerLaunchingTest.cs

test/integration/ServerTests/AppiumLocalServerLaunchingTest.cs already using System.Text;
Therefore we can simplify Encoding.UTF8.GetString

chore: Simplify member access in AppiumLocalServerLaunchingTest

---

src/Appium.Net/Appium.Net.csproj

-Bump Selenium NuGets from 4.5.1 to 4.11.0
- [] New feature (non-breaking change which adds functionality)

build(deps): bump Selenium from 4.5.1 to 4.11.0

---

test/integration/Android/ActivityTest.cs
test/integration/Android/AppStringsTest.cs
test/integration/Android/ConnectionTest.cs
test/integration/Android/FileInteractionTest.cs
test/integration/Android/SessionTest.cs

typo fix and remove unnecessary usings from android integration tests
- [] Bugfix (non-breaking change which fixes an issue)

chore: typo fix and remove unnecessary usings 

---

.gitignore

Autogenerated .logs files are not needed for tracking 

chore: add *.log to .gitignore

---

test/integration/Android/Device/PerformanceDataTests.cs

removed unnecessary usings from android/device/PerformanceDataTests 

chore: remove unnecessary usings from PerformanceDataTests

---

src/Appium.Net/Appium/Enums/AutomationName.cs

remove unnecessary usings from AutomationName 

chore: remove unnecessary usings from AutomationName

---

test/integration/ServerTests/StartingAppLocallyTest.cs

test: typo fix in ServerTests/StartingAppLocallyTest.cs

---

README.md

found out that we are using rel/5.0 branche for build status piepline.

Fix: change branch name to main on build status

---

test/integration/ServerTests/StartingAppLocallyTest.cs

fix: add missing AutomationName to client capabilities
chore: replace deprecated closeApp with TerminateApp

test: add missing AutomationName to client capabilities and replace deprecated methods

---

PULL_REQUEST_TEMPLATE.md

docs: Update Writing on GitHub link in PULL_REQUEST_TEMPLATE.md

---

.github/dependabot.yml

We can use the benefits of Dependabot version updates for our project.

GitHub: Add dependabot to Repo

---

.github/labeler.yml

GitHub: Add chore label

---

test/integration/helpers/Caps.cs

iOS caps are outdated and had to be updated in order to run iOS unit tests on newer machines.

fix: Update iOS Caps

---

README.md

Added an Apache license badge and made some re-ordering on the badges

docs: Add Apache badge and some re-ordering 

---

azure-pipelines.yml

ci: Run all AppiumLocalServerLaunchingTest

---

README.md

chore: add Help wanted badge

---

.github/release-drafter.yml

since we are in RC stages we can add prerelease to release-drafter 
https://github.com/release-drafter/release-drafter#prerelease-increment

github: Add prerelease increment to release-drafter

---

.github/labeler.yml

github: add GitHub labeler

---

.github/release-drafter.yml

Added Maintenance category in release-drafter

chore: add Maintenance category in release-drafter.yml

---

test/integration/Android/Device/KeyboardTests.cs

We were missing a test coverage for IsKeyBoardShown()

test: add IsKeyBoardShown Test

---

src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
src/Appium.Net/Appium/Interfaces/IInteractsWithApps.cs
test/integration/Android/Device/KeyPressTest.cs
test/integration/helpers/Apps.cs

removed ResetApp() + made some refactoring along the way on the `helpers/Apps` for better clarity and efficiency 
related to https://github.com/appium/appium/issues/15807

chore: Remove resetApp

---

src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/AppiumElement.cs

The XML documentation for the Rotate method was badly formatted, a fix was needed to properly display the documentation.

chore: Fix Rotate XML documentation

---

.github/workflows/release-nuget.yml

Update .NET Core version to 5.0.x in release-nuget.yml

[github-actions] Update .NET Core version to 5.0.x in release-nuget.yml

---

README.md

- Added Deprecated Methods section 
- Migration Guide to W3C actions example 
- Added alerts Markdown extension: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
- Some grammar fixes …

docs: Add Release Candidate information

---

test/integration/Windows/ImagesComparisonTest.cs

Fixed test assertions on the test/integration/Windows/ImagesComparisonTest.cs after the latest NUnit Update

test: fix tests assertions

---

src/Appium.Net/Appium.Net.csproj
src/Appium.Net/Appium/Service/AppiumLocalService.cs

WebRequest and HttpWebRequest are obsolete, we need to use HttpClient instead. 

refactor: Replace obsolete WebRequest,HttpWebRequest with HttpClient

---

src/Appium.Net/Appium.Net.csproj
test/integration/Android/ActionsChainsTest.cs

- add missing Apache header 
- reorganize using and add ambiguous comments
- replace MouseButton.Touch with proper PointerButton.TouchContact
- add test TouchByCoordinatesTestCase()

test: add TouchByCoordinatesTestCase

---

test/integration/Android/ClipboardTest.cs

chore: Identifiers should not contain underscores
chore: replace deprecated App management methods
chore: add SupportedOSPlatform attribute

chore: ClipboardTest fixes and improvements

---

src/Appium.Net/Appium/AppiumOptions.cs
test/integration/Options/OptionsTest.cs

Fix  for https://github.com/appium/dotnet-client/issues/724

fix: Include missing AppiumOptionsDictionary into ToDictionary

---

README.md

Take the headers out of the alerts markups 

docs: fix headers in README.md

---

src/Appium.Net/Appium/Service/AppiumServiceBuilder.cs

- remove unused private methods 
- fix CA2208 warnings
- fix IDE0031 warnings
- fix CS8073 warning
- fix CA1822 warning
- fix IDE0049 warning

chore: warning fixes in AppiumServiceBuilder.cs

---

test/integration/Android/CurrentPackageTest.cs

Replace deprecated app management methods 

test: replace deprecated methods in test/integration/Android/CurrentPackageTest.cs

---

azure-pipelines.yml

Add DirectConnectTest to pipeline

ci: Add DirectConnectTest to pipeline

---

src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
src/Appium.Net/Appium/AppiumElement.cs
test/integration/Android/OrientationTest.cs

Since Rotate is not implemented, it's misleading to have the option to call this endpoint.
This PR will remove any related code 
See related PR: https://github.com/appium/appium/pull/19379
See related issue: https://github.com/appium/dotnet-client/issues/755
Please provide more details about changes if it is necessary. You can provide code samples showing how they work and possible use cases if there are new features. Also, you can create [gists](https://gist.github.com) with pasted C# code samples or put them here using markdown.  …

chore: Remove Rotate endpoint

---

src/Appium.Net.sln
src/Appium.Net/Appium.Net.csproj

Address https://github.com/appium/dotnet-client/issues/738

docs: Add README.md to Appium.Net.csproj

---

src/Appium.Net/Appium/Android/Enums/AndroidKeyMetastate.cs

Add missing XML comments for the members in the `AndroidKeyMetastate` class

docs: add missing XML comments in the AndroidKeyMetastate class

---

test/integration/Android/ClipboardTest.cs

Add missing test for SetClipboardImage method

test: Add missing test for SetClipboardImage method

---

src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/AppiumDriver.cs
src/Appium.Net/Appium/AppiumDriverCommand.cs
src/Appium.Net/Appium/Interfaces/IInteractsWithApps.cs
src/Appium.Net/Appium/Windows/WindowsDriver.cs
test/integration/Android/Device/AuthenticationTest.cs

Removal of the LaunchApp API and last remaining test

chore: Remove deprecated LaunchApp

---

src/Appium.Net/Appium/AppiumCommand.cs

Create a region for Applications Management 

chore: Organize app management endpoints

---

test/integration/Android/Device/KeyboardTests.cs

Add a test for the HideKeyboard(string key) method

test: Add a test for HideKeyboard(string key) method

---

test/integration/env.json.sample

Remove old wd/hub from remoteAppiumServerUri in the `env.json.sample` file

chore: Remove wd/hub from env.json.sample

---

test/integration/Android/Session/GeolocationTests.cs

Fix assertions in GeolocationTests

test: Fix assertions in GeolocationTests

---

test/integration/Android/Session/SessionTests.cs
test/integration/Android/SessionTest.cs

Fix Session Tests
Rename and move to the appropriate test folder 

Test: Fix Session tests

---

test/integration/Android/Device/PerformanceDataTests.cs

stabilize GetPerformanceDataTest and add assert messages 

test: stabilize GetPerformanceDataTest and add assert messages

---

test/integration/IOS/SettingTest.cs

test: Remove unnecessary using and fix namespace in iOS setting test

---

test/integration/Android/ActionsChainsTest.cs
test/integration/Android/ClipboardTest.cs
test/integration/IOS/ClipboardTest.cs
test/integration/Windows/PentTest.cs

- Add Drawing Category to related tests
- Remove redundant using

test: Add new Drawing Category to related tests

---

.github/labeler.yml

github: Add Breaking Change labeler

---

src/Appium.Net/Appium/AppiumCommand.cs
src/Appium.Net/Appium/Windows/WindowsDriver.cs
src/Appium.Net/Appium/Windows/WindowsDriverCommand.cs

Bring back the `LaunchApp` Command to `WindowsDriver`

feat: Bring back `LaunchApp` to `WindowsDriver`

---

.github/labeler.yml

Update title for BREAKING CHANGE

github: Update Breaking Change title in labeler.yml

---

.github/labeler.yml

github: Fix Breaking Change label to match Release Drafter

---

test/integration/Android/CurrentPackageTest.cs

fix(test): add explicit wait for app package to load before assertion

---

src/Appium.Net/Appium.Net.csproj

- Remove Selenium.Support package as a dependency
Seems this package is unnecessary.

build(deps): Remove Selenium.Support package as a dependency

---

Appium.Net.sln

- Move solution to the root folder
Improvement. I will just git clone, open my IDE, and it opens.

chore: Move solution to the root folder

---

.github/release-drafter.yml

display new contributors at the end of the release notes under the "New Contributors" section.

github: include a notification for new contributors

---

.github/workflows/release-nuget.yml

Due to changes on https://github.com/appium/dotnet-client/pull/844, need to update the release-nuget as well 

github: Fix .sln path for release-nuget.yml

---

.github/release-drafter.yml

github: Fix New Contributors var

---

README.md

- Add v6.0.0 to the Compatibility Matrix
- update .NET Version

docs: Add v6.0.0 to Compatibility Matrix

---

src/Appium.Net/Appium/Android/Enums/AndroidKeyCode.cs
test/integration/Android/ActivityTest.cs
test/integration/Android/Device/BrowserTests.cs
test/integration/Options/OptionsTest.cs

Fix namespaces to match folder
Fix ContactsActivity name
- [] Have you provided integration tests for your changes? (required for Bugfix, New feature, or Test fix) …

test: Adjust tests namespaces to match folder structure

---

test/integration/IOS/SearchingTest.cs

remove deprecated ByIosUIAutomation test
fix assertion on text

test: fix IOS/SearchingTest

---

test/integration/IOS/AlertTests.cs

update alert text assertion to use correct newline character

test: update alert text assertion in IOS/AlertTests

---

README.md

Update the compatibility matrix for the Appium .NET version 7

docs: Update the compatibility matrix

---

test/integration/IOS/OrientationTest.cs

refactor OrientationTest to improve teardown logic and reset orientation 

test: Add reset orientation in teardown to iOS OrientationTest

---

test/integration/env.json.sample

correct formatting in env.json.sample for remoteAppiumServerUri

fix: correct formatting in env.json.sample for remoteAppiumServerUri

---

.github/release-drafter.yml

Added a "🧪 Tests" section under categories to automatically include PRs labeled as Test or Tests.
Ensured consistency with existing categories.

github: Added a "🧪 Tests" section

---

src/Appium.Net/Appium/Interfaces/IHidesKeyboardWithKeyName.cs
src/Appium.Net/Appium/iOS/IOSDriver.cs
test/integration/IOS/Device/KeyboardTests.cs

Add the new keyword to hide inhierted method (Remove Warning)
Added missing iOS keyboard tests for HideKeyboard functionality

test: add iOS keyboard tests for HideKeyboard functionality

---

azure-pipelines.yml

Fix .NET core unit tests run
Add AppiumClientConfigTest to pipeline 

ci: Fix .NET Core run and add AppiumClientConfigTest to pipeline

---

src/Appium.Net/Appium/AppiumCommand.cs

Adds comments to replace with extensions, or remove for Appium 3 era. https://github.com/appium/appium/issues/20792
I haven't checked the actual implementation side to see if some of them are already logged to remove, replace, etc. At least most of them should be sufficient to replace with extensions.
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and …

chore: add todo comments in AppiumCommand.cs for future reference

---

src/Appium.Net/Appium/Android/AndroidDriver.cs
src/Appium.Net/Appium/AppiumCommandExecutionHelper.cs
src/Appium.Net/Appium/Interfaces/IHasClipboard.cs

XML comments fixes (AppiumCommandExecutionHelper.cs).
Inspired by #733.

chore: Fix XML comments in AppiumCommandExecutionHelper.cs
